=== ArturSierakowski/Projects/ArtistPage/main.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" 
elementFormDefault="qualified">
    <xs:element name="main">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="author" type="authorType" minOccurs="0" maxOccurs="1" />
				<xs:element name="section" type="sectionType" minOccurs="0" maxOccurs="unbounded" />				
				<xs:element name="images" type="imagesType" minOccurs="0" maxOccurs="1" />
				<xs:element name="media" type="mediaType" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>	
	</xs:element>

	<xs:complexType name="authorType">
		<xs:sequence>
			<xs:element name="name" type="shortStringType" />
			<xs:element name="surname">
				<xs:simpleType>
					<xs:union memberTypes="shortStringType minLengthType" />
				</xs:simpleType>
			</xs:element>			
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="shortStringType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="minLengthType">
		<xs:restriction base="xs:string">
			<xs:minLength value="2" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="sectionType">
		<xs:sequence>
			<xs:element name="art" type="artType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="drawings" type="drawingsType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="contact" type="contactType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute ref="kind" use="required" />
	</xs:complexType>
	
	<xs:attribute name="kind" type="kindType" />
		<xs:simpleType name="kindType">
			<xs:restriction base="xs:string">
				<xs:enumeration value="content" />
				<xs:enumeration value="information" />
			</xs:restriction>
		</xs:simpleType>
	
	<xs:complexType name="artType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="drawingsType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1" />			
			<xs:element name="table" type="tableType" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="contactType">
		<xs:sequence>
			<xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tableType">
		<xs:sequence>
			<xs:element name="list" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="drawing" type="xs:string" minOccurs="1" maxOccurs="5" />
                    </xs:sequence>
                    <xs:attribute name="order" type="orderType" />
                </xs:complexType>
            </xs:element>            
		</xs:sequence>
		<xs:attribute name="id" type="xs:unsignedByte" use="required"/>
	</xs:complexType>	
	
	 <xs:simpleType name="orderType">
        <xs:restriction base="xs:string">
            <xs:pattern value="dates|alphabetical" />
        </xs:restriction>
    </xs:simpleType>
	
	<xs:complexType name="imagesType">
        <xs:sequence>
          <xs:element name="image" type="imageType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
		
		<xs:complexType name="imageType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="source" type="xs:anyURI" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="image" type="imageType" />
	
	<xs:complexType name="mediaType">
        <xs:sequence>
           <xs:element name="links" type="linksType" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>
		
	<xs:complexType name="linksType">
		<xs:sequence>
			<xs:element ref="link" minOccurs="3" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="linkType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="important" type="importantType" use="required" />
				<xs:attribute name="source" type="xs:anyURI" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="link" type="linkType" />

	<xs:simpleType name="importantType">
        <xs:restriction base="xs:string">
            <xs:pattern value="yes|no" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== ArturSierakowski/Projects/ArtistPage/main.xml
<?xml version="1.0" encoding="utf-8"?>

<main xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="main.xsd">
	<author>
		<name>Artur</name>
		<surname>Sierakowski</surname>
	</author>

	<section kind="information">
			<art>
				<title>Czym jest sztuka</title>
				<text>
					Nie istnieje powszechnie przyjęta definicja sztuki. Często używamy słowa "sztuka" do opisywania pięknego przedmiotu lub umiejętności pozwalającej wytworzyć przedmiot o wysokich walorach estetycznych. Patrząc w ten sposób, moglibyśmy więc całymi godzinami spierać się o to, czym jest sztuka. I prawdopodobnie mielibyśmy problem z osiągnięciem jakiegoś zadowalającego konsensusu.
					Choć nie ma jednej uniwersalnej definicji sztuki, istnieje ogólna zgoda, że jest ona świadomym działaniem mającym na celu stworzenie czegoś pięknego lub znaczącego (w taki czy inny sposób) przy użyciu wyobraźni oraz umiejętności.
					Warto w tym miejscu zaznaczyć, że postrzeganie sztuki zmieniało się na przestrzeni kolejnych wieków oraz w zależności od kultury, jaką moglibyśmy rozpatrywać. Obraz autorstwa Jean-Michel Basquiat, który sprzedano za 110,5 miliona dolarów na aukcji Sotheby w maju 2017 roku, bez wątpienia nie zostałby uznany za dzieło sztuki na przykład w renesansowych Włoszech.
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sit amet varius nunc, ut commodo nisi. Nunc hendrerit maximus iaculis. Aenean et erat purus. Nam accumsan orci a ante lacinia gravida. Praesent finibus lectus sit amet sapien pellentesque, ac suscipit tellus pellentesque. Maecenas magna leo, tempor at ligula vel, congue consequat augue. Praesent bibendum lorem iaculis metus aliquet cursus. Ut id feugiat nisl, ac cursus turpis. Pellentesque ultrices enim felis, sed posuere ex luctus quis. Proin in turpis neque. Mauris porta tempor lacinia. Aenean fringilla condimentum lacus sit amet placerat. Nam tincidunt ligula et tempor maximus. Aliquam non massa quis ante suscipit pellentesque vel sit amet odio. Nullam sit amet leo neque. Vivamus lacinia enim felis, hendrerit cursus enim convallis quis.
					Morbi ut sagittis magna, et aliquam magna. Integer pulvinar pulvinar sem lacinia tempus. Nam quis tincidunt libero, eget lacinia felis. Etiam feugiat fringilla auctor. Mauris odio tellus, maximus sit amet elementum a, egestas quis neque. Duis tincidunt scelerisque porttitor. Vivamus dictum nunc eget justo efficitur, condimentum interdum dolor efficitur. Quisque consequat iaculis felis, in tincidunt lorem dictum id. Sed mollis ligula ut mi porttitor pretium sit amet ut nulla. Fusce eget imperdiet turpis. Fusce eget maximus quam.
					Nullam at tortor lobortis, tempus massa a, congue ex. Nulla suscipit tincidunt leo sodales commodo. Sed quis bibendum enim, nec porttitor ex. Curabitur non ornare diam, sed fringilla leo. Phasellus egestas commodo urna in interdum. Suspendisse sit amet euismod dolor, et pharetra odio. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis semper neque in sapien tristique, ac eleifend nisi accumsan. Proin venenatis turpis at ante tempor pharetra. Fusce faucibus neque at eleifend tincidunt. Vestibulum auctor nulla eget ante mattis ullamcorper.
					Integer condimentum neque non dignissim condimentum. Nulla nec turpis quis felis venenatis dignissim et ut dui. In eget felis augue. Donec finibus dui mi, facilisis posuere libero dignissim non. Nulla consequat malesuada tortor, et tincidunt neque lacinia suscipit. Donec vitae est lorem. Sed blandit, leo quis aliquam blandit, sapien mi tempor orci, et elementum est velit quis orci. Sed malesuada nunc metus, at eleifend dui aliquet ac. Morbi non ornare ante.
					Donec commodo hendrerit posuere. Sed accumsan et sapien nec vestibulum. Pellentesque sit amet facilisis neque. Mauris mollis mi convallis, dignissim ipsum in, laoreet dolor. Nullam eu erat nisi. In vel diam id dolor mollis dignissim vel ut tellus. Pellentesque nec odio dui. Curabitur eget quam ligula. Etiam egestas, nulla eu rhoncus mollis, lacus risus bibendum ipsum, eu posuere velit tortor nec nisi. Pellentesque ut accumsan mi. Donec non nibh tincidunt, fringilla ipsum sit amet, sollicitudin ex.
				</text>
			</art>
			<contact>
				<title>Kontakt</title>
				<text>
					Jeśli chciałbyś zaproponować temat następnej pracy lub nawiązać współpracę zapraszam do kontaktu mailowego na adres blabla@poczta.com.
					Zachęcam również do zapoznania się z poniższymi mediami społecznościowymi, na których umieszczam nowe rysunki oraz tutoriale.
				</text>				
			</contact>
	</section>

	<section kind="content">
			<drawings>
				<title>Moja galeria</title>
				<table id="1">
					<list order="alphabetical">
						<drawing>domin</drawing>
						<drawing>nemo</drawing>
						<drawing>nieskonczony</drawing>
						<drawing>portret</drawing>
						<drawing>rysunek</drawing>			
					</list>
				</table>
			</drawings>
	</section>

	<images>
		<image source="img/main.jpg"></image>
		<image source="img/portret.jpg"></image>
		<image source="img/nieskonczony.jpg"></image>
		<image source="img/domin.jpg"></image>
		<image source="img/rysunek.jpg"></image>
		<image source="img/nemo.jpg"></image>
	</images>

	<media>
		<links>
			<link important="yes" source="https://facebook.com/">Facebook</link>
			<link important="yes" source="https://instagram.com/">Instagram</link>
			<link important="yes" source="https://youtube.com">Youtube</link>
			<link important="yes" source="https://pinterest.com/">Pinterest</link>
		</links>
	</media>
</main>
